services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started

  app:
    image: imrankhani/docker-compose-app:1.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.app
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: ${POSTGRES_DB}
    secrets:
      - db_password
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 256m
    cpus: "0.50"

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: appdb
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data-v2:/var/lib/postgresql

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  postgres-data-v2:
